# Generated by Django 4.0.5 on 2022-06-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('light', models.CharField(max_length=100)),
                ('water', models.CharField(max_length=100)),
                ('toxic', models.BooleanField()),
                ('description', models.TextField(max_length=500)),
                ('picture', models.URLField(max_length=1000)),
            ],
        ),
    ]
