# Generated by Django 4.0.5 on 2022-06-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='picture',
        ),
        migrations.AddField(
            model_name='plant',
            name='detailPicture',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='indexPicture',
            field=models.URLField(max_length=1000, null=True),
        ),
    ]
