# Generated by Django 4.0.5 on 2022-06-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_plant_picture_plant_detailpicture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='toxic',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1),
        ),
    ]
