# Generated by Django 4.0.5 on 2022-06-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_pot_plant_pots'),
    ]

    operations = [
        migrations.AddField(
            model_name='pot',
            name='color',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='pot',
            name='material',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='pot',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pot',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pot',
            name='size',
            field=models.IntegerField(null=True),
        ),
    ]
