# Generated by Django 4.0.5 on 2022-06-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_pot_color_pot_material_pot_name_pot_price_pot_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='pots',
            field=models.ManyToManyField(blank=True, to='main_app.pot'),
        ),
    ]
